position = [ 109.875, 83.1 ]
is_flipped = false
has_model = true
is_tht_or_smd = true
has_paste = true
pad_type = "SMD"
shape = "ROUNDRECT"
size = [ 1.025, 1.4 ]
rotation = 0.0
roundness = 0.243902
drill_shape = "OVAL"
drill_size = [ 0.0, 0.0 ]
fab_type = "NONE"
