position = [ 134.525, 91.8 ]
is_flipped = true
has_model = true
is_tht_or_smd = true
has_paste = true
pad_type = "SMD"
shape = "ROUNDRECT"
size = [ 1.2, 1.4 ]
rotation = 1.5707963267948966
roundness = 0.208333
drill_shape = "OVAL"
drill_size = [ 0.0, 0.0 ]
fab_type = "NONE"
