position = [ 130.2375, 89.95 ]
is_flipped = true
has_model = true
is_tht_or_smd = true
has_paste = true
pad_type = "SMD"
shape = "ROUNDRECT"
size = [ 1.175, 1.45 ]
rotation = 3.141592653589793
roundness = 0.212766
drill_shape = "OVAL"
drill_size = [ 0.0, 0.0 ]
fab_type = "NONE"
