position = [ 123.45, 87.7 ]
is_flipped = true
has_model = true
is_tht_or_smd = true
has_paste = true
pad_type = "SMD"
shape = "ROUNDRECT"
size = [ 1.2, 1.4 ]
rotation = 3.141592653589793
roundness = 0.208333
drill_shape = "OVAL"
drill_size = [ 0.0, 0.0 ]
fab_type = "NONE"
