position = [ 142.91, 97.615 ]
is_flipped = false
has_model = true
is_tht_or_smd = true
has_paste = true
pad_type = "SMD"
shape = "ROUNDRECT"
size = [ 1.32, 0.59 ]
rotation = 0.0
roundness = 0.125
drill_shape = "OVAL"
drill_size = [ 0.0, 0.0 ]
fab_type = "NONE"
