position = [ 128.28, 86.475 ]
is_flipped = true
has_model = true
is_tht_or_smd = true
has_paste = true
pad_type = "SMD"
shape = "RECT"
size = [ 0.76, 0.22 ]
rotation = 0.0
roundness = 0.0
drill_shape = "OVAL"
drill_size = [ 0.0, 0.0 ]
fab_type = "NONE"
