position = [ 129.265, 87.275 ]
is_flipped = true
has_model = true
is_tht_or_smd = true
has_paste = false
pad_type = "SMD"
shape = "RECT"
size = [ 0.9, 1.5 ]
rotation = 0.0
roundness = 0.0
drill_shape = "OVAL"
drill_size = [ 0.0, 0.0 ]
fab_type = "NONE"
