position = [ 150.2, 82.2125 ]
is_flipped = true
has_model = true
is_tht_or_smd = true
has_paste = true
pad_type = "SMD"
shape = "ROUNDRECT"
size = [ 0.975, 1.4 ]
rotation = 4.71238898038469
roundness = 0.25
drill_shape = "OVAL"
drill_size = [ 0.0, 0.0 ]
fab_type = "NONE"
