position = [ 158.960499, 79.900563 ]
is_flipped = false
has_model = true
is_tht_or_smd = true
has_paste = true
pad_type = "SMD"
shape = "RECT"
size = [ 1.4732, 0.3556 ]
rotation = 0.0
roundness = 0.25
drill_shape = "OVAL"
drill_size = [ 0.0, 0.0 ]
fab_type = "NONE"
