position = [ 107.65, 71.665 ]
is_flipped = false
has_model = false
is_tht_or_smd = false
has_paste = false
pad_type = "NPTH"
shape = "CIRCLE"
size = [ 2.1, 2.1 ]
rotation = 0.0
roundness = 0.25
drill_shape = "OVAL"
drill_size = [ 2.1, 2.1 ]
fab_type = "NONE"
