position = [ 146.05, 93.9 ]
is_flipped = true
has_model = true
is_tht_or_smd = true
has_paste = true
pad_type = "SMD"
shape = "ROUNDRECT"
size = [ 2.5, 1.8 ]
rotation = 3.141592653589793
roundness = 0.1388888889
drill_shape = "OVAL"
drill_size = [ 0.0, 0.0 ]
fab_type = "NONE"
