position = [ 157.725, 97.05 ]
is_flipped = false
has_model = true
is_tht_or_smd = true
has_paste = false
pad_type = "THT"
shape = "CIRCLE"
size = [ 1.6, 1.6 ]
rotation = 0.0
roundness = 0.25
drill_shape = "OVAL"
drill_size = [ 0.8, 0.8 ]
fab_type = "NONE"
