position = [ 155.185, 97.05 ]
is_flipped = false
has_model = true
is_tht_or_smd = true
has_paste = false
pad_type = "THT"
shape = "RECT"
size = [ 1.5, 1.5 ]
rotation = 0.0
roundness = 0.25
drill_shape = "OVAL"
drill_size = [ 0.8, 0.8 ]
fab_type = "NONE"
