position = [ 156.5, 87.679763 ]
is_flipped = false
has_model = true
is_tht_or_smd = true
has_paste = true
pad_type = "SMD"
shape = "RECT"
size = [ 1.2, 1.2 ]
rotation = 3.141592653589793
roundness = 0.25
drill_shape = "OVAL"
drill_size = [ 0.0, 0.0 ]
fab_type = "NONE"
