position = [ 122.175, 69.975 ]
is_flipped = false
has_model = false
is_tht_or_smd = false
has_paste = false
pad_type = "SMD"
shape = "RECT"
size = [ 1.0, 1.0 ]
rotation = 0.0
roundness = 0.25
drill_shape = "OVAL"
drill_size = [ 0.0, 0.0 ]
fab_type = "NONE"
