position = [ 111.33, 70.535 ]
is_flipped = false
has_model = true
is_tht_or_smd = true
has_paste = true
pad_type = "THT"
shape = "OVAL"
size = [ 1.0, 1.8 ]
rotation = 3.141592653589793
roundness = 0.25
drill_shape = "UNKNOWN"
drill_size = [ 0.6, 1.4 ]
fab_type = "HEATSINK"
